### PR TITLE
Add a TunableController

### PR DESCRIPTION
**Pull request by JosephTLockwood**
Add a TunableController with Docs

### CODE REVIEW

**Comment by JosephTLockwood** [comment]
Closes #20

**Comment by JosephTLockwood** [comment]
@CrispyBacon1999 Please check.

**Review by cosmosified — COMMENTED** [review]
seems neat. what are you using this for in your system?

**Review by cosmosified — APPROVED** [review]

**Comment by JosephTLockwood** [comment]
> seems neat. what are you using this for in your system?

We will be using this to replace our normal drive controller. We like how the robot feels driving when we make the joystick essentially exponential. It gives us much more control over the lower-end speeds.

**Pull request merged**
